import React from 'react';
import PageSEO from '../components/PageSEO';

const TermsOfService: React.FC = () => {
  return (
    <div className="bg-white dark:bg-slate-950 min-h-screen pt-32 pb-24 transition-colors">
      <PageSEO 
        title="Terms of Service | ProductDetailer" 
        description="Read our Terms of Service regarding the use of ProductDetailer." 
      />
       <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white mb-4">Terms of Service</h1>
          <p className="text-slate-600 dark:text-slate-400 mb-12">Last updated: November 15, 2023</p>
          
          <div className="prose prose-lg dark:prose-invert max-w-none text-slate-600 dark:text-slate-300">
             <p>Please read these terms and conditions carefully before using Our Service.</p>
             
             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Acknowledgment</h2>
             <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
             <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
             
             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">User Accounts</h2>
             <p>When You create an account with Us, You must provide Us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of Your account on Our Service.</p>
             <p>You are responsible for safeguarding the password that You use to access the Service and for any activities or actions under Your password.</p>

             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Intellectual Property</h2>
             <p>The Service and its original content (excluding Content provided by You or other users), features and functionality are and will remain the exclusive property of the Company and its licensors.</p>
             <p>The content generated by our AI for you is yours to use for commercial purposes.</p>

             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Termination</h2>
             <p>We may terminate or suspend Your Account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
             <p>Upon termination, Your right to use the Service will cease immediately.</p>

             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Limitation of Liability</h2>
             <p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever.</p>

             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Changes to These Terms and Conditions</h2>
             <p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect.</p>

             <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-12 mb-6">Contact Us</h2>
             <p>If you have any questions about these Terms and Conditions, You can contact us:</p>
             <ul className="list-disc pl-6 space-y-2">
                <li>By email: contact@productdetailer.com</li>
             </ul>
          </div>
       </div>
    </div>
  );
};
export default TermsOfService;